name: Slack Notification on Push to Staging or Main

on:
  push:
    branches:
      - main
      - staging

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Send Slack Message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            MESSAGE="New pushes to the main branch!"
          elif [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            MESSAGE="New pushes to the staging branch!"
          else
            MESSAGE="New pushes to an unspecified branch."
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"$MESSAGE\"
          }" $SLACK_WEBHOOK_URL
